"""empty message

Revision ID: b99d7854f776
Revises: 225f0f21fec7
Create Date: 2021-10-22 11:15:27.831978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99d7854f776'
down_revision = '225f0f21fec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('name_favorite', sa.String(length=30), nullable=False))
    op.drop_column('user', 'name_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_favorite', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('favorite', 'name_favorite')
    # ### end Alembic commands ###
